#+TITLE: Chatting with the Community

The System Crafters community hangs out in a few places, YouTube comments (and live chat on streams), Discord, and IRC (also accessible with a Matrix bridge).

* YouTube
You can chat with us during [[https://www.youtube.com/channel/UCAiiOTio8Yu69c3XnR7nQBQ][System Crafters live streams]]!

* Discord
This is currently where the bulk of the community is hanging out. There are several emacs and guix focused topic channels as well as general topic channels like gaming, music, and showcases of what the community is up to. Here is the invite [[https://discord.gg/EfBzP8bV][link to Discord]].

* IRC / Matrix bridge
** Internet Relay Chat (IRC)
[[ircs://irc.libera.chat/systemcrafters][#systemcrafters]] channel is on the [[https://libera.chat][libera.chat]] irc server along with a lot of other FOSS software channels like [[ircs://irc.libera.chat/emacs][#emacs]], [[ircs://irc.libera.chat/guix][#guix]], etc.
*** Join via ERC
You can join the [[ircs://irc.libera.chat/systemcrafters][#systemcrafters]] channel from within Emacs. For a quick introduction, have a look at [[https://www.youtube.com/watch?v=qWHTZIYTA4s][Chat Like the 90's in Emacs with ERC]], but for the impatient, you can use the following sexp:

#+begin_src emacs-lisp
  (erc-tls :server "irc.libera.chat"
                    :port 6697
                    :nick   "YOUR-NICK"
                    :full-name "YOUR-FULL-NAME")
#+end_src

After your initial connection, use =/join #systemcrafters= to join the systemcrafters channel. For more information, see the [[info:erc][ERC manual]] or the [[https://www.emacswiki.org/emacs/ERC][ERC page in the Emacs Wiki]].

** Matrix bridge
Some may prefer to access the IRC channel using the [[https://en.wikipedia.org/wiki/Matrix_(protocol)][[matrix] protocol]] clients like [[https://element.io/][Element]]. Matrix bridges allow other protocols to be bridged with matrix. Matrix clients have an UX more similar to Discord and have some benefits like: it serves as a built-in bounce server (so you can see messages when you weren't online), it _supports_ /inline/ *markup* +or+ and ~code~ snippets, and the mobile app support is better. 
There are a few different ways to achieve this:

*** Join as a Matrix user
You can join a room directly by adding ~#systemcrafters:irc.libera.chat~ to join with your matrix identity. You don't have to register with IRC at all if you just want to keep using your matrix identity since both Matrix and IRC users are treated as first class citizens.

*** Join as an IRC user
In order to use Matrix you have to have a Matrix account but if once logged into the client (Element) you can invite @NickServ:libera.chat to a PM to register/identify your IRC nick. Then invite @appservice:libera.chat to a PM and ~!join #systemscrafters~. In order to save your username by issuing the ~!username~ command followed by the ~!storepass YourP@assw0rd~.

It's also a good idea to cloak your user (so your IP address is hidden from a ~whois~ query). You can do that by ~/join #libera-cloak~ and then sending the message ~!cloakme~. You only need to do it once for your NickServ account and it will cloak your all your nicks anytime you connect.


Follow libera.chat guidance on grouping your nicks under a single NickServ account if you plan on signing into IRC from Matrix and an IRC client simultaneously (https://libera.chat/guides/registration#registering).
=NOTE= If you join as more than one sure please append an underscore to your secondary nick which should be the same as your primary nick. This will help everyone understand it's the same person in two different clients. Example: =daviwil= and =daviwil_=.

=NOTE=: libera.chat IRC server does not support ~COMMAND setname~ which is what allows you to set your "real name" after connecting. And the Element client does not pass a ~realname~ as part of the connection string. So unfortunately your real name will show as your Matrix username.

*** Join as all the things
You could join from an IRC client and through Matrix and authenticate as an IRC user and you can join from Matrix as a Matrix user, just join.
