#+TITLE: Welcome to the System Crafters Wiki!

This site is a collaborative effort by the System Crafters community
to provide useful resources for system crafting with GNU Emacs, GNU
Guix, and all other related tools.  There are also resources for how
you can connect with other members of the community over Discord,
Matrix, and IRC!

* Topics

** [[emacs/][GNU Emacs]]

Information regarding Emacs configuration and various packages.

** [[guix/][GNU Guix]]

Overview of the GNU Guix operating system and information regarding
installation and packages.

** [[articles/][All Articles]]

A master list of all articles if you prefer searching/exploring in
there yourself.

* Our community

** [[community/getting-involved/][Getting involved]]

Ways that you can contribute to the System Crafters wiki.

** [[community/chat-with-us/][Chatting with the community]]

How to get in touch with other members of the System Crafters
community on various platforms.

** [[community/code-of-conduct/][Code of Conduct]]

Guidelines for the System Crafters wiki.

* Why not use [some other wiki]?

We decided to make this a site instead of use GitHub wiki, Sourcehut
man, or other sites so that we can more easily control the
presentation and also provide this content in other offline forms.
We're open to suggestions too!
